In [2]:
import pandas as pd

In [7]:
orders = pd.read_csv('OrderItems.csv')
deliveries = pd.read_csv('Deliveries.csv')

In [8]:
df = orders.merge(deliveries[["OrderID", "LineID", "DeliveryStatus"]], 
                  on=["OrderID", "LineID"], 
                  how="left")

In [9]:
df

,OrderID,LineID,ItemCode,ItemCategory,Quantity,UnitPrice,RequestedDate,LineAmount,DeliveryStatus
0,500001,1,SKU-4743,Consumables,89,51.90,2024-12-18,4619.10,Late
1,500002,1,SKU-1567,Software,17,29.38,2024-04-17,499.46,On Time
2,500003,1,SKU-4456,Equipment,240,83.20,2024-04-06,19968.00,On Time
3,500004,1,SKU-8598,Software,82,28.72,2025-04-09,2355.04,Late
4,500004,2,SKU-1695,Software,203,33.40,2025-04-26,6780.20,Late
...,...,...,...,...,...,...,...,...,...
4491,501798,3,SKU-8139,Consumables,167,63.13,2024-09-18,10542.71,Late
4492,501798,4,SKU-2300,Hardware,100,57.98,2024-09-26,5798.00,On Time
4493,501799,1,SKU-5972,Equipment,144,55.13,2025-09-07,7938.72,Late
4494,501800,1,SKU-2358,Hardware,166,27.27,2024-08-07,4526.82,On Time
4495,501800,2,SKU-9960,Software,183,51.72,2024-07-14,9464.76,Late

In [17]:
x = df.drop(columns=["DeliveryStatus"]) # Features (all columns except "DeliveryStatus")
y = df["is_late"] # Target variable (1 if order is late, 0 otherwise)

In [12]:
df

,OrderID,LineID,ItemCode,ItemCategory,Quantity,UnitPrice,RequestedDate,LineAmount,DeliveryStatus,is_late
0,500001,1,SKU-4743,Consumables,89,51.90,2024-12-18,4619.10,Late,1
1,500002,1,SKU-1567,Software,17,29.38,2024-04-17,499.46,On Time,0
2,500003,1,SKU-4456,Equipment,240,83.20,2024-04-06,19968.00,On Time,0
3,500004,1,SKU-8598,Software,82,28.72,2025-04-09,2355.04,Late,1
4,500004,2,SKU-1695,Software,203,33.40,2025-04-26,6780.20,Late,1
...,...,...,...,...,...,...,...,...,...,...
4491,501798,3,SKU-8139,Consumables,167,63.13,2024-09-18,10542.71,Late,1
4492,501798,4,SKU-2300,Hardware,100,57.98,2024-09-26,5798.00,On Time,0
4493,501799,1,SKU-5972,Equipment,144,55.13,2025-09-07,7938.72,Late,1
4494,501800,1,SKU-2358,Hardware,166,27.27,2024-08-07,4526.82,On Time,0
4495,501800,2,SKU-9960,Software,183,51.72,2024-07-14,9464.76,Late,1

In [ ]:
y = df["is_late"]

In [14]:
y

0       1
1       0
2       0
3       1
4       1
       ..
4491    1
4492    0
4493    1
4494    0
4495    1
Name: is_late, Length: 4496, dtype: int64

In [15]:
y.type()

AttributeError: 'Series' object has no attribute 'type'

In [16]:
x

,OrderID,LineID,ItemCode,ItemCategory,Quantity,UnitPrice,RequestedDate,LineAmount
0,500001,1,SKU-4743,Consumables,89,51.90,2024-12-18,4619.10
1,500002,1,SKU-1567,Software,17,29.38,2024-04-17,499.46
2,500003,1,SKU-4456,Equipment,240,83.20,2024-04-06,19968.00
3,500004,1,SKU-8598,Software,82,28.72,2025-04-09,2355.04
4,500004,2,SKU-1695,Software,203,33.40,2025-04-26,6780.20
...,...,...,...,...,...,...,...,...
4491,501798,3,SKU-8139,Consumables,167,63.13,2024-09-18,10542.71
4492,501798,4,SKU-2300,Hardware,100,57.98,2024-09-26,5798.00
4493,501799,1,SKU-5972,Equipment,144,55.13,2025-09-07,7938.72
4494,501800,1,SKU-2358,Hardware,166,27.27,2024-08-07,4526.82
4495,501800,2,SKU-9960,Software,183,51.72,2024-07-14,9464.76

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y,  test_size=0.2) #20% of data for testing, 80% for training

In [19]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y,  test_size=0.2) #20% of data for testing, 80% for training

In [22]:
x_train

,OrderID,LineID,ItemCode,ItemCategory,Quantity,UnitPrice,RequestedDate,LineAmount,is_late
156,500066,1,SKU-7935,Services,180,54.30,2024-01-30,9774.00,1
397,500161,3,SKU-3403,Equipment,80,72.37,2025-04-05,5789.60,1
2026,500803,2,SKU-3271,Hardware,40,36.62,2024-03-02,1464.80,0
3377,501328,1,SKU-6215,Hardware,39,47.03,2024-07-03,1834.17,1
1896,500753,2,SKU-4240,Software,195,42.81,2026-01-24,8347.95,0
...,...,...,...,...,...,...,...,...,...
3083,501213,1,SKU-4747,Hardware,32,16.34,2024-04-04,522.88,0
4407,501768,1,SKU-3213,Software,221,37.43,2024-08-14,8272.03,1
1556,500625,2,SKU-8534,Consumables,196,55.45,2025-02-17,10868.20,1
1885,500750,3,SKU-1948,Services,69,27.26,2025-10-30,1880.94,1
2808,501106,2,SKU-2678,Services,186,35.49,2025-11-03,6601.14,0

In [24]:
from sklearn.preprocessing import StandardScaler # not necessary for tree-based models like Random Forest, but good practice for other models
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [25]:
model = RandomForestClassifier()

In [27]:
model.fit(x_train, y_train)

ValueError: could not convert string to float: 'SKU-7935'

In [28]:
x.columns

Index(['OrderID', 'LineID', 'ItemCode', 'ItemCategory', 'Quantity',
       'UnitPrice', 'RequestedDate', 'LineAmount', 'is_late'],
      dtype='object')

In [29]:
x_train

,OrderID,LineID,ItemCode,ItemCategory,Quantity,UnitPrice,RequestedDate,LineAmount,is_late
156,500066,1,SKU-7935,Services,180,54.30,2024-01-30,9774.00,1
397,500161,3,SKU-3403,Equipment,80,72.37,2025-04-05,5789.60,1
2026,500803,2,SKU-3271,Hardware,40,36.62,2024-03-02,1464.80,0
3377,501328,1,SKU-6215,Hardware,39,47.03,2024-07-03,1834.17,1
1896,500753,2,SKU-4240,Software,195,42.81,2026-01-24,8347.95,0
...,...,...,...,...,...,...,...,...,...
3083,501213,1,SKU-4747,Hardware,32,16.34,2024-04-04,522.88,0
4407,501768,1,SKU-3213,Software,221,37.43,2024-08-14,8272.03,1
1556,500625,2,SKU-8534,Consumables,196,55.45,2025-02-17,10868.20,1
1885,500750,3,SKU-1948,Services,69,27.26,2025-10-30,1880.94,1
2808,501106,2,SKU-2678,Services,186,35.49,2025-11-03,6601.14,0

In [30]:
x.drop(columns=["OrderID", "LineID", "is_late"], inplace=True)

In [31]:
x

      ItemCode ItemCategory  Quantity  UnitPrice RequestedDate  LineAmount
0     SKU-4743  Consumables        89      51.90    2024-12-18     4619.10
1     SKU-1567     Software        17      29.38    2024-04-17      499.46
2     SKU-4456    Equipment       240      83.20    2024-04-06    19968.00
3     SKU-8598     Software        82      28.72    2025-04-09     2355.04
4     SKU-1695     Software       203      33.40    2025-04-26     6780.20
...        ...          ...       ...        ...           ...         ...
4491  SKU-8139  Consumables       167      63.13    2024-09-18    10542.71
4492  SKU-2300     Hardware       100      57.98    2024-09-26     5798.00
4493  SKU-5972    Equipment       144      55.13    2025-09-07     7938.72
4494  SKU-2358     Hardware       166      27.27    2024-08-07     4526.82
4495  SKU-9960     Software       183      51.72    2024-07-14     9464.76

[4496 rows x 6 columns]

In [34]:
x.drop(columns=["ItemCode"], inplace=True)

In [35]:
x

     ItemCategory  Quantity  UnitPrice RequestedDate  LineAmount
0     Consumables        89      51.90    2024-12-18     4619.10
1        Software        17      29.38    2024-04-17      499.46
2       Equipment       240      83.20    2024-04-06    19968.00
3        Software        82      28.72    2025-04-09     2355.04
4        Software       203      33.40    2025-04-26     6780.20
...           ...       ...        ...           ...         ...
4491  Consumables       167      63.13    2024-09-18    10542.71
4492     Hardware       100      57.98    2024-09-26     5798.00
4493    Equipment       144      55.13    2025-09-07     7938.72
4494     Hardware       166      27.27    2024-08-07     4526.82
4495     Software       183      51.72    2024-07-14     9464.76

[4496 rows x 5 columns]

In [36]:
x_train, x_test, y_train, y_test = train_test_split(x, y,  test_size=0.2) #20% of data for testing, 80% for training

In [37]:
x_train

     ItemCategory  Quantity  UnitPrice RequestedDate  LineAmount
4467     Services       127      24.44    2024-06-01     3103.88
619   Consumables        53      64.50    2025-08-30     3418.50
3998     Software        51     109.17    2025-09-04     5567.67
1571    Equipment        89      26.92    2025-01-26     2395.88
2255     Hardware       189      39.71    2024-01-17     7505.19
...           ...       ...        ...           ...         ...
2053     Services        30      40.41    2024-03-27     1212.30
952      Hardware       175      94.19    2024-07-27    16483.25
215      Services       177      79.37    2024-06-14    14048.49
1961    Equipment       248      90.32    2025-01-07    22399.36
2930     Software        12      47.07    2024-07-25      564.84

[3596 rows x 5 columns]

In [38]:
x_test

     ItemCategory  Quantity  UnitPrice RequestedDate  LineAmount
2214    Equipment       179      36.52    2025-03-15     6537.08
3394     Software        25     104.03    2025-04-18     2600.75
2711     Software       204      53.04    2025-10-30    10820.16
4195     Services       243      82.77    2025-10-06    20113.11
2063    Equipment       182      52.06    2025-01-18     9474.92
...           ...       ...        ...           ...         ...
1878     Hardware       185      42.54    2025-05-12     7869.90
1377  Consumables        62      35.14    2025-08-06     2178.68
3175     Services       185      43.03    2025-01-03     7960.55
3875     Services        52      28.52    2025-07-29     1483.04
3278     Hardware       154      60.91    2024-05-13     9380.14

[900 rows x 5 columns]

In [39]:
y_train, y_test

(4467    1
 619     1
 3998    0
 1571    1
 2255    1
        ..
 2053    1
 952     0
 215     0
 1961    1
 2930    1
 Name: is_late, Length: 3596, dtype: int64,
 2214    1
 3394    1
 2711    1
 4195    1
 2063    0
        ..
 1878    1
 1377    0
 3175    1
 3875    0
 3278    1
 Name: is_late, Length: 900, dtype: int64)

In [40]:
model.fit(x_train, y_train)

ValueError: could not convert string to float: 'Services'

In [45]:
x = pd.get_dummies(x, columns=["ItemCategory"]).astype(int) # Convert ItemCategory to numbers
# Convert RequestedDate to numeric (extract useful parts)
x["RequestedDate"] = pd.to_datetime(x["RequestedDate"])
x["Month"] = x["RequestedDate"].dt.month
x["DayOfWeek"] = x["RequestedDate"].dt.dayofweek
x = x.drop("RequestedDate", axis=1)

KeyError: "None of [Index(['ItemCategory'], dtype='object')] are in the [columns]"

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y,  test_size=0.2) #20% of data for testing, 80% for training

In [43]:
x_train

,Quantity,UnitPrice,LineAmount,ItemCategory_Consumables,ItemCategory_Equipment,ItemCategory_Hardware,ItemCategory_Services,ItemCategory_Software,Month,DayOfWeek
4416,120,82.67,9920.40,False,True,False,False,False,10,4
1339,233,97.40,22694.20,False,False,True,False,False,10,2
4313,80,31.93,2554.40,False,False,False,True,False,9,1
1478,203,30.88,6268.64,False,False,False,False,True,8,4
20,104,68.17,7089.68,False,False,False,False,True,12,5
...,...,...,...,...,...,...,...,...,...,...
840,180,51.51,9271.80,False,False,False,False,True,11,0
4269,192,75.44,14484.48,False,False,True,False,False,4,0
1627,217,69.05,14983.85,False,False,False,False,True,2,5
3338,170,60.65,10310.50,False,False,True,False,False,7,1
4369,249,62.70,15612.30,True,False,False,False,False,7,5

KeyError: "None of [Index(['ItemCategory'], dtype='object')] are in the [columns]"

In [46]:
x = pd.get_dummies(x, columns=["ItemCategory_Consumables"]).astype(int)

In [47]:
x.columns

Index(['Quantity', 'UnitPrice', 'LineAmount', 'ItemCategory_Equipment',
       'ItemCategory_Hardware', 'ItemCategory_Services',
       'ItemCategory_Software', 'Month', 'DayOfWeek',
       'ItemCategory_Consumables_False', 'ItemCategory_Consumables_True'],
      dtype='object')

In [49]:
x = pd.get_dummies(x, columns=["ItemCategory_Hardware","ItemCategory_Software" , "ItemCategory_Equipment" , "ItemCategory_Consumables_False", "ItemCategory_Consumables_True"  ]).astype(int)

In [50]:
x

,Quantity,UnitPrice,LineAmount,ItemCategory_Services,Month,DayOfWeek,ItemCategory_Hardware_0,ItemCategory_Hardware_1,ItemCategory_Software_0,ItemCategory_Software_1,ItemCategory_Equipment_0,ItemCategory_Equipment_1,ItemCategory_Consumables_False_0,ItemCategory_Consumables_False_1,ItemCategory_Consumables_True_0,ItemCategory_Consumables_True_1
0,89,51,4619,0,12,2,1,0,1,0,1,0,1,0,0,1
1,17,29,499,0,4,2,1,0,0,1,1,0,0,1,1,0
2,240,83,19968,0,4,5,1,0,1,0,0,1,0,1,1,0
3,82,28,2355,0,4,2,1,0,0,1,1,0,0,1,1,0
4,203,33,6780,0,4,5,1,0,0,1,1,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,167,63,10542,0,9,2,1,0,1,0,1,0,1,0,0,1
4492,100,57,5798,0,9,3,0,1,1,0,1,0,0,1,1,0
4493,144,55,7938,0,9,6,1,0,1,0,0,1,0,1,1,0
4494,166,27,4526,0,8,2,0,1,1,0,1,0,0,1,1,0
4495,183,51,9464,0,7,6,1,0,0,1,1,0,0,1,1,0

In [51]:
x = df.drop(columns=["DeliveryStatus"])

In [52]:
x

,OrderID,LineID,ItemCode,ItemCategory,Quantity,UnitPrice,RequestedDate,LineAmount,is_late
0,500001,1,SKU-4743,Consumables,89,51.90,2024-12-18,4619.10,1
1,500002,1,SKU-1567,Software,17,29.38,2024-04-17,499.46,0
2,500003,1,SKU-4456,Equipment,240,83.20,2024-04-06,19968.00,0
3,500004,1,SKU-8598,Software,82,28.72,2025-04-09,2355.04,1
4,500004,2,SKU-1695,Software,203,33.40,2025-04-26,6780.20,1
...,...,...,...,...,...,...,...,...,...
4491,501798,3,SKU-8139,Consumables,167,63.13,2024-09-18,10542.71,1
4492,501798,4,SKU-2300,Hardware,100,57.98,2024-09-26,5798.00,0
4493,501799,1,SKU-5972,Equipment,144,55.13,2025-09-07,7938.72,1
4494,501800,1,SKU-2358,Hardware,166,27.27,2024-08-07,4526.82,0
4495,501800,2,SKU-9960,Software,183,51.72,2024-07-14,9464.76,1

In [53]:
x.drop(columns=["OrderID", "LineID", "is_late", "ItemCode"], inplace=True)

In [54]:
x

     ItemCategory  Quantity  UnitPrice RequestedDate  LineAmount
0     Consumables        89      51.90    2024-12-18     4619.10
1        Software        17      29.38    2024-04-17      499.46
2       Equipment       240      83.20    2024-04-06    19968.00
3        Software        82      28.72    2025-04-09     2355.04
4        Software       203      33.40    2025-04-26     6780.20
...           ...       ...        ...           ...         ...
4491  Consumables       167      63.13    2024-09-18    10542.71
4492     Hardware       100      57.98    2024-09-26     5798.00
4493    Equipment       144      55.13    2025-09-07     7938.72
4494     Hardware       166      27.27    2024-08-07     4526.82
4495     Software       183      51.72    2024-07-14     9464.76

[4496 rows x 5 columns]

In [55]:
# Fix requested date
x["RequestedDate"] = pd.to_datetime(x["RequestedDate"])
x["Month"] = x["RequestedDate"].dt.month
x["DayOfWeek"] = x["RequestedDate"].dt.dayofweek
x["Year"] = x["RequestedDate"].dt.year
x.drop(columns=["RequestedDate"], inplace=True)

In [56]:
x

     ItemCategory  Quantity  UnitPrice  LineAmount  Month  DayOfWeek  Year
0     Consumables        89      51.90     4619.10     12          2  2024
1        Software        17      29.38      499.46      4          2  2024
2       Equipment       240      83.20    19968.00      4          5  2024
3        Software        82      28.72     2355.04      4          2  2025
4        Software       203      33.40     6780.20      4          5  2025
...           ...       ...        ...         ...    ...        ...   ...
4491  Consumables       167      63.13    10542.71      9          2  2024
4492     Hardware       100      57.98     5798.00      9          3  2024
4493    Equipment       144      55.13     7938.72      9          6  2025
4494     Hardware       166      27.27     4526.82      8          2  2024
4495     Software       183      51.72     9464.76      7          6  2024

[4496 rows x 7 columns]

In [57]:
#Make the categorical variable into dummy variables
x = pd.get_dummies(x, columns=["ItemCategory"]).astype(int)

In [58]:
x

,Quantity,UnitPrice,LineAmount,Month,DayOfWeek,Year,ItemCategory_Consumables,ItemCategory_Equipment,ItemCategory_Hardware,ItemCategory_Services,ItemCategory_Software
0,89,51,4619,12,2,2024,1,0,0,0,0
1,17,29,499,4,2,2024,0,0,0,0,1
2,240,83,19968,4,5,2024,0,1,0,0,0
3,82,28,2355,4,2,2025,0,0,0,0,1
4,203,33,6780,4,5,2025,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
4491,167,63,10542,9,2,2024,1,0,0,0,0
4492,100,57,5798,9,3,2024,0,0,1,0,0
4493,144,55,7938,9,6,2025,0,1,0,0,0
4494,166,27,4526,8,2,2024,0,0,1,0,0
4495,183,51,9464,7,6,2024,0,0,0,0,1

In [59]:
x_train, x_test, y_train, y_test = train_test_split(x, y,  test_size=0.2) #20% of data for testing, 80% for training

In [60]:
model.fit(x_train, y_train)

RandomForestClassifier()

In [61]:
importances = pd.Series(model.feature_importances_, index=x_train.columns)
print(importances.sort_values(ascending=False))

LineAmount                  0.234647
Quantity                    0.223860
UnitPrice                   0.212481
Month                       0.124200
DayOfWeek                   0.097098
Year                        0.036208
ItemCategory_Software       0.015228
ItemCategory_Hardware       0.015085
ItemCategory_Services       0.013893
ItemCategory_Equipment      0.013699
ItemCategory_Consumables    0.013601
dtype: float64



##### The Big Three — Numeric Features Dominate

| Feature | Importance | Insight |
|---|---|---|
| `LineAmount` | 23% | High value orders are the strongest signal |
| `Quantity` | 22% | How many units ordered matters almost as much |
| `UnitPrice` | 21% | Price per unit is nearly equally important |

---

##### Time Features — Matter but Less

| Feature | Importance | Insight |
|---|---|---|
| `Month` | 12% | Seasonality plays a role — certain months are worse |
| `DayOfWeek` | 10% | Day of week has some influence |
| `Year` | 4% | Minimal impact |

---

##### 🏷️ Category Features — Barely Matter (~1–2% each)

All `ItemCategory_*` columns rank at the bottom with very low importance.

> Whether an order is **Software, Hardware, Services, Equipment, or Consumables** does not strongly predict lateness.

---

###### 💡 Key Takeaway

> **Large, expensive, high-quantity orders are most likely to run late.**
>
> Any order where both `LineAmount` and `Quantity` are high should be flagged as a lateness risk **before it ships**.

In [62]:
from sklearn.metrics import classification_report
print(classification_report(y_test, model.predict(x_test)))

              precision    recall  f1-score   support

           0       0.46      0.46      0.46       407
           1       0.55      0.55      0.55       493

    accuracy                           0.51       900
   macro avg       0.50      0.50      0.50       900
weighted avg       0.51      0.51      0.51       900

#### Model was only 51% accurate due to the data being random/syntheic (There was no real business logic implemented with the creation of the dataset)